apiVersion: v1
kind: Service
metadata:
  name: blackbox-targets
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
spec:
  ports:
    - name: http
      port: 9115
      targetPort: 9115
