apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-etnair
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /probe
      interval: 15s
      params:
        module: [http_2xx]
      relabelings:
        # 1) on prend l'endpoint (ip:port) du service blackbox-targets
        - sourceLabels: [__meta_kubernetes_endpoints_name]
          regex: blackbox-targets
          action: keep

        # 2) fabriquer target = http://IP:PORT/ selon le port name
        - sourceLabels: [__meta_kubernetes_endpoint_address_target_name, __meta_kubernetes_endpoint_port_number]
          separator: ':'
          targetLabel: __param_target
          replacement: http://$1:$2/

        # 3) on envoie la probe au blackbox exporter
        - targetLabel: __address__
          replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

        # 4) label instance = target probé
        - sourceLabels: [__param_target]
          targetLabel: instance
