apiVersion: v1
kind: ConfigMap
metadata:
  name: etnair-frontend-nginx
  namespace: etnair
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location /api/ {
        proxy_pass http://etnair-api:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        try_files $uri $uri/ /index.html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etnair-frontend
  namespace: etnair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etnair-frontend
  template:
    metadata:
      labels:
        app: etnair-frontend
    spec:
      containers:
        - name: frontend
          image: karl123/etnair-frontend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: etnair-frontend-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: etnair-frontend
  namespace: etnair
spec:
  type: NodePort
  selector:
    app: etnair-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30420
