apiVersion: v1
kind: Namespace
metadata:
  name: etnair
---
# ===========================
# SECRETS
# ===========================
apiVersion: v1
kind: Secret
metadata:
  name: etnair-secret
  namespace: etnair
type: Opaque
stringData:
  POSTGRES_USER: etnair_user
  POSTGRES_PASSWORD: etnair_pass
  POSTGRES_DB: etnair_db
  JWT_SECRET: dev_secret

  # ===== MinIO / S3 =====
  S3_ENDPOINT: http://minio:9000
  S3_REGION: us-east-1
  S3_ACCESS_KEY: minioadmin
  S3_SECRET_KEY: minioadmin123
  S3_BUCKET: etnair

  # URL publique VM
  S3_PUBLIC_BASE_URL: http://172.16.250.11:30900/etnair
---
# ===========================
# POSTGRES PVC
# ===========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etnair-postgres-pvc
  namespace: etnair
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ===========================
# POSTGRES DEPLOYMENT
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: etnair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: etnair-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etnair-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: etnair-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: etnair-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: etnair
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
---
# ===========================
# MINIO PVC
# ===========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etnair-minio-pvc
  namespace: etnair
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ===========================
# MINIO DEPLOYMENT
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: etnair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-08-04T17-40-21Z
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: etnair-secret
                  key: S3_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etnair-secret
                  key: S3_SECRET_KEY
          ports:
            - containerPort: 9000
              name: s3
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: etnair-minio-pvc
---
# ===========================
# MINIO SERVICE (NODEPORT)
# ===========================
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: etnair
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
      nodePort: 30900
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901
---
# ===========================
# MINIO INIT JOB (PUBLIC BUCKET)
# ===========================
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: etnair
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mc
          image: minio/mc:RELEASE.2023-08-04T17-51-16Z
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: etnair-secret
                  key: S3_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etnair-secret
                  key: S3_SECRET_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: etnair-secret
                  key: S3_BUCKET
          command: ["sh", "-c"]
          args:
            - |
              set -euo pipefail
              echo "Waiting for MinIO..."
              for i in $(seq 1 60); do
                if mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" --api S3v4 >/dev/null 2>&1; then
                  echo "MinIO reachable."
                  break
                fi
                sleep 2
              done
              mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" --api S3v4
              mc mb -p "local/$S3_BUCKET" || true
              cat > /tmp/public.json <<EOF
              {
                "Version":"2012-10-17",
                "Statement":[{
                  "Effect":"Allow",
                  "Principal":"*",
                  "Action":["s3:GetObject"],
                  "Resource":["arn:aws:s3:::${S3_BUCKET}/*"]
                }]
              }
              EOF
              mc anonymous set-json /tmp/public.json "local/$S3_BUCKET" || true
              echo "MinIO bucket ready."
---
# ===========================
# ETNAIR API
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etnair-api
  namespace: etnair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etnair-api
  template:
    metadata:
      labels:
        app: etnair-api
    spec:
      containers:
        - name: api
          image: karl123/etnair-api:1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgresql://etnair_user:etnair_pass@postgresql:5432/etnair_db"
          envFrom:
            - secretRef:
                name: etnair-secret
---
apiVersion: v1
kind: Service
metadata:
  name: etnair-api
  namespace: etnair
spec:
  type: NodePort
  selector:
    app: etnair-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
