apiVersion: v1
kind: PersistentVolume
metadata:
  name: etnair-minio-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/etnair/minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etnair-minio-pvc
  namespace: etnair
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: etnair-minio-pv
